heat_template_version: 2013-05-23

description: Test template.

parameters:
  net_id:
    type: string
    label: Net ID
    description: Network ID for the server
    default: 03e0e92e-d2b9-4c2b-b0fc-98a5a773818e

  instance_name:
    type: string
    label: Instance Name
    description: Name of the instance.
    default: test01

resources:
  the_server:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance_name }
      key_name: CloudKey
      image: "ubuntu-heat-cfntools"
      flavor: m1.small
      networks:
        - network: "03e0e92e-d2b9-4c2b-b0fc-98a5a773818e"
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash -v

            yum -y install mariadb mariadb-server
            touch /var/log/mariadb/mariadb.log
            chown mysql.mysql /var/log/mariadb/mariadb.log
            systemctl start mariadb.service

            # Setup MySQL root password and create a user
            mysqladmin -u root password db_rootpassword
            cat << EOF | mysql -u root --password=db_rootpassword
            CREATE DATABASE db_name;
            GRANT ALL PRIVILEGES ON db_name.* TO "db_user"@"%"
            IDENTIFIED BY "db_password";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          params:
            db_rootpassword: { get_param: db_root_password }
            db_name: { get_param: db_name }
            db_user: { get_param: db_username }
            db_password: { get_param: db_password }


 
outputs:
  instance_ip:
    description: IP for test instance.
    value:
      str_replace:
        template: host
        params:
          host: { get_attr: [the_server, networks, private, 0] }
